Refactor build process from Python to JavaScript
nk2028/tshet-uinh-examples pull request #78
Opened 2024-11-28 07:12 UTC by graphemecluster

- Replace Python build script with JavaScript
  - The `選項` argument of `from字頭` now accepts both objects and arrays. (Allowing specifying objects is purely for backward compatibility.) Results are outputted as both array elements and named properties. Closes #77.
- Check coverage during building and testing (Fixes #71)
- Separate type definitions to the dedicated file such that they are recognised when called in a TypeScript file
- Move generated artifacts to a `dist` directory and make the npm package include only this directory

2024-11-28 10:39 UTC, syimyuzya requested changes

2024-11-28 10:39 UTC, syimyuzya commented on eslint.config.js
> -    ignores: ['index.js'],
Should be `ignores: ['dist/**/*'],`

2024-11-28 10:39 UTC, syimyuzya commented on package.json
> +    "lint:fix": "eslint --fix . --ignore-pattern dist/**",
The path pattern should go to the ESLint config. (See eslint.config.js)

2024-11-28 10:39 UTC, syimyuzya commented on package.json
> +	},
Inconsistent indentation

2024-11-28 10:59 UTC, syimyuzya commented
Also, that "Python" in the VSCode extension recommendations can be removed (and replaced by ESLint).

2024-12-05 06:33 UTC, syimyuzya commented on package.json
> +    "lint:fix": "eslint --fix . --ignore-pattern dist/**",
Makes sense 😃

2024-12-05 06:36 UTC, syimyuzya requested changes

2024-12-05 06:36 UTC, syimyuzya commented on package.json
> +    "lint:fix": "eslint --fix . --ignore-pattern dist/**",
The pattern should be `dist/**/*`.

2024-12-05 06:39 UTC, syimyuzya commented on package.json
> +	},
```suggestion
  "main": "./dist/index.js",
  "types": "./dist/index.d.ts",
  "exports": {
    ".": {
      "default": "./dist/index.js",
      "types": "./dist/index.d.ts"
    }
  },
```

2024-12-05 06:45 UTC, graphemecluster commented
@syimyuzya 你 commit 啦，我這幾天 AFK 😄

2024-12-05 06:48 UTC, syimyuzya commented
> @syimyuzya 你 commit 啦，我這幾天 AFK 😄

好嗒～

2024-12-05 06:51 UTC, syimyuzya approved these changes

2024-12-05 06:53 UTC, merged